openapi: 3.0.0
info:
  title: Authenticator
  description: >-
    Especificações da API para o back-end da aplicação "Authenticator".
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Status:
      type: string
      enum:
        - active
        - inactive
    BasicResponse:
      type: object
      properties:
        feedback:
          type: string
      required:
        - feedback
      additionalProperties: false
    BasicCreationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        feedback:
          type: string
      required:
        - id
        - feedback
      additionalProperties: false

    Error:
      type: object
      properties:
        feedback:
          type: string
      required:
        - feedback
      additionalProperties: false
    Unauthorized:
      type: object
      properties:
        feedback:
          type: string
      required:
        - feedback
      additionalProperties: false
    InternalServerError:
      type: object
      properties:
        feedback:
          type: string
      required:
        - feedback
      additionalProperties: false

    LoginCredentials:
      type: object
      properties:
        application:
          type: string
          format: uuid
          x-go-extra-tags:
            validate: required
        email:
          type: string
          format: email
          x-go-extra-tags:
            validate: required
        password:
          type: string
          format: password
          x-go-extra-tags:
            validate: required,min=8,max=32
      required:
        - application
        - email
        - password
      additionalProperties: false
    LoginResponse:
      type: object
      properties:
        feedback:
          type: string
        token:
          type: string
      required:
        - token
        - feedback
      additionalProperties: false

    NewUser:
      type: object
      properties:
        name:
          type: string
          x-go-extra-tags:
            validate: required,min=3
        email:
          type: string
          format: email
          x-go-extra-tags:
            validate: required,email
        password:
          type: string
          format: password
          x-go-extra-tags:
            validate: required,min=8,max=32
      required:
        - name
        - email
        - password
      additionalProperties: false
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        status:
          $ref: "#/components/schemas/Status"
      required:
        - name
        - email
        - status
      additionalProperties: false
    NewUserStatus:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status"
      required:
        - status
      additionalProperties: false

    NewApplication:
      type: object
      properties:
        name:
          type: string
          x-go-extra-tags:
            validate: required
      required:
        - name
      additionalProperties: false
    Application:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      required:
        - id
        - name
      additionalProperties: false

    NewGroup:
      type: object
      properties:
        name:
          type: string
          x-go-extra-tags:
            validate: required,min=3
      required:
        - name
        - applicationId
      additionalProperties: false
    Group:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        permissions:
          type: object
          properties:
            any:
              description: As chaves desse objeto serão as keys da aplicação. Utilize GET /applications/{id} para verificar.
              type: string

paths:
  /login:
    post:
      summary: Autentica usuário
      tags:
        - session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginCredentials"
      responses:
        "200":
          description: Token de autenticação
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /users:
    get:
      security:
        - bearerAuth: []
      summary: Lista todos os usuários
      tags:
        - users
      responses:
        "200":
          description: Lista dos usuários cadastrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
    post:
      security:
        - bearerAuth: []
      summary: Cadastra um novo usuário
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
      responses:
        "201":
          description: Usuário cadastrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /users/{byEmail}:
    patch:
      security:
        - bearerAuth: []
      summary: Atualiza o status de um usuário
      tags:
        - users
      parameters:
        - in: path
          name: byEmail
          schema:
            type: string
            format: email
            x-go-extra-tags:
              validate: required,email
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUserStatus"
      responses:
        "200":
          description: Resposta vazia
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /applications:
    get:
      security:
        - bearerAuth: []
      summary: Lista todas as aplicações
      tags:
        - applications
      responses:
        "200":
          description: Lista das aplicações cadastrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Application"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
    post:
      security:
        - bearerAuth: []
      summary: Cadastra uma aplicação
      tags:
        - applications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewApplication"
      responses:
        "201":
          description: Aplicação cadastrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicCreationResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /applications/{id}:
    get:
      security:
        - bearerAuth: []
      summary: Informações de uma aplicação
      tags:
        - applications
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          x-go-extra-tags:
            validate: required,uuid
          required: true
      responses:
        "200":
          description: Informações da aplicação
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /applications/{id}/groups:
    get:
      security:
        - bearerAuth: []
      summary: Lista os grupos de permissões de um aplicativo
      tags:
        - groups
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          x-go-extra-tags:
            validate: required,uuid
          required: true
      responses:
        "200":
          description: Lista grupos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicCreationResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
    post:
      security:
        - bearerAuth: []
      summary: Cadastra um novo grupo de permissões para um aplicativo
      tags:
        - groups
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          x-go-extra-tags:
            validate: required,uuid
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewGroup"
      responses:
        "201":
          description: Grupo cadastrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicCreationResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
