openapi: 3.0.0
info:
  title: Authenticator
  description: >-
    Especificações da API para o back-end da aplicação "Authenticator" da
    empresa emnuvem
  version: 1.0.0
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          x-go-extra-tags:
            validate: required,min=3
        email:
          type: string
          format: email
          x-go-extra-tags:
            validate: required,email
        password:
          type: string
          format: password
          x-go-extra-tags:
            validate: required,min=8
      required:
        - name
        - email
        - password
      additionalProperties: false
    UserData:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
      required:
        - name
        - email
      additionalProperties: false
    Error:
      type: object
      properties:
        feedback:
          type: string
      required:
        - feedback
      additionalProperties: false

paths:
  /users:
    get:
      summary: Lista todos os usuários
      tags:
        - users
      responses:
        "200":
          description: Lista dos usuários cadastrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserData"

    post:
      summary: Cadastra um novo usuário
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: Resposta vazia
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
